modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Kizunad/Guzhenren-ext/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Kizunad/Guzhenren-ext"
logoFile="logo.jpg"
authors="${mod_authors}"
description="${mod_description}"

[[mods]]
modId="customnpcs"
version="1.0.0"
displayName="Custom NPCs AI System"
authors="Kizunad"
description="Autonomous NPC AI system with Utility AI and memory"
